{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Captcha exposing
    ( captchaChallenge
    , captchaImage
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


captchaChallenge : Api.Request Api.Data.Challenge
captchaChallenge =
    Api.request
        "GET"
        "/captcha/challenge/"
        []
        []
        []
        Nothing
        Api.Data.challengeDecoder


captchaImage : String -> Api.Request ()
captchaImage id_path =
    Api.request
        "GET"
        "/captcha/{id}/image/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())
