{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Common exposing
    ( commonDepartmentCreate
    , commonDepartmentDelete
    , commonDepartmentList
    , commonDepartmentPartialUpdate
    , commonDepartmentRead
    , commonDepartmentUpdate
    , commonOrganizationCreate
    , commonOrganizationDelete
    , commonOrganizationList
    , commonOrganizationPartialUpdate
    , commonOrganizationRead
    , commonOrganizationUpdate
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


commonDepartmentCreate : Api.Data.Department -> Api.Request Api.Data.Department
commonDepartmentCreate data_body =
    Api.request
        "POST"
        "/common/department/"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDepartment data_body)))
        Api.Data.departmentDecoder


commonDepartmentDelete : Uuid -> Api.Request ()
commonDepartmentDelete id_path =
    Api.request
        "DELETE"
        "/common/department/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


commonDepartmentList : Api.Request (List Api.Data.Department)
commonDepartmentList =
    Api.request
        "GET"
        "/common/department/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.departmentDecoder)


commonDepartmentPartialUpdate : Uuid -> Api.Data.Department -> Api.Request Api.Data.Department
commonDepartmentPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/common/department/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDepartment data_body)))
        Api.Data.departmentDecoder


commonDepartmentRead : Uuid -> Api.Request Api.Data.Department
commonDepartmentRead id_path =
    Api.request
        "GET"
        "/common/department/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.departmentDecoder


commonDepartmentUpdate : Uuid -> Api.Data.Department -> Api.Request Api.Data.Department
commonDepartmentUpdate id_path data_body =
    Api.request
        "PUT"
        "/common/department/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeDepartment data_body)))
        Api.Data.departmentDecoder


commonOrganizationCreate : Api.Data.Organization -> Api.Request Api.Data.Organization
commonOrganizationCreate data_body =
    Api.request
        "POST"
        "/common/organization/"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrganization data_body)))
        Api.Data.organizationDecoder


commonOrganizationDelete : Uuid -> Api.Request ()
commonOrganizationDelete id_path =
    Api.request
        "DELETE"
        "/common/organization/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


commonOrganizationList : Api.Request (List Api.Data.Organization)
commonOrganizationList =
    Api.request
        "GET"
        "/common/organization/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.organizationDecoder)


commonOrganizationPartialUpdate : Uuid -> Api.Data.Organization -> Api.Request Api.Data.Organization
commonOrganizationPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/common/organization/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrganization data_body)))
        Api.Data.organizationDecoder


commonOrganizationRead : Uuid -> Api.Request Api.Data.Organization
commonOrganizationRead id_path =
    Api.request
        "GET"
        "/common/organization/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        Nothing
        Api.Data.organizationDecoder


commonOrganizationUpdate : Uuid -> Api.Data.Organization -> Api.Request Api.Data.Organization
commonOrganizationUpdate id_path data_body =
    Api.request
        "PUT"
        "/common/organization/{id}/"
        [ ( "id", Uuid.toString id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeOrganization data_body)))
        Api.Data.organizationDecoder
