{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Course exposing
    ( courseCreate
    , courseDelete
    , courseEnrollmentCreate
    , courseEnrollmentDelete
    , courseEnrollmentList
    , courseEnrollmentPartialUpdate
    , courseEnrollmentRead
    , courseEnrollmentUpdate
    , courseGetDeep
    , courseList
    , courseListDeep
    , coursePartialUpdate
    , courseRead
    , courseUpdate
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


courseCreate : Api.Data.CourseShallow -> Api.Request Api.Data.CourseShallow
courseCreate data_body =
    Api.request
        "POST"
        "/course/"
        []
        []
        []
        (Just (Api.Data.encodeCourseShallow data_body))
        Api.Data.courseShallowDecoder


courseDelete : String -> Api.Request ()
courseDelete id_path =
    Api.request
        "DELETE"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


courseEnrollmentCreate : Api.Data.CourseEnrollmentWrite -> Api.Request Api.Data.CourseEnrollmentWrite
courseEnrollmentCreate data_body =
    Api.request
        "POST"
        "/course/enrollment/"
        []
        []
        []
        (Just (Api.Data.encodeCourseEnrollmentWrite data_body))
        Api.Data.courseEnrollmentWriteDecoder


courseEnrollmentDelete : String -> Api.Request ()
courseEnrollmentDelete id_path =
    Api.request
        "DELETE"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


courseEnrollmentList : Api.Request (List Api.Data.CourseEnrollmentRead)
courseEnrollmentList =
    Api.request
        "GET"
        "/course/enrollment/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.courseEnrollmentReadDecoder)


courseEnrollmentPartialUpdate : String -> Api.Data.CourseEnrollmentRead -> Api.Request Api.Data.CourseEnrollmentRead
courseEnrollmentPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourseEnrollmentRead data_body))
        Api.Data.courseEnrollmentReadDecoder


courseEnrollmentRead : String -> Api.Request Api.Data.CourseEnrollmentRead
courseEnrollmentRead id_path =
    Api.request
        "GET"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.courseEnrollmentReadDecoder


courseEnrollmentUpdate : String -> Api.Data.CourseEnrollmentWrite -> Api.Request Api.Data.CourseEnrollmentWrite
courseEnrollmentUpdate id_path data_body =
    Api.request
        "PUT"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourseEnrollmentWrite data_body))
        Api.Data.courseEnrollmentWriteDecoder


courseGetDeep : String -> Api.Request Api.Data.CourseDeep
courseGetDeep id_path =
    Api.request
        "GET"
        "/course/{id}/deep/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.courseDeepDecoder


courseList : Api.Request (List Api.Data.CourseShallow)
courseList =
    Api.request
        "GET"
        "/course/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.courseShallowDecoder)


courseListDeep : Api.Request Api.Data.CourseDeep
courseListDeep =
    Api.request
        "GET"
        "/course/deep/"
        []
        []
        []
        Nothing
        Api.Data.courseDeepDecoder


coursePartialUpdate : String -> Api.Data.CourseShallow -> Api.Request Api.Data.CourseShallow
coursePartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourseShallow data_body))
        Api.Data.courseShallowDecoder


courseRead : String -> Api.Request Api.Data.CourseShallow
courseRead id_path =
    Api.request
        "GET"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.courseShallowDecoder


courseUpdate : String -> Api.Data.CourseShallow -> Api.Request Api.Data.CourseShallow
courseUpdate id_path data_body =
    Api.request
        "PUT"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourseShallow data_body))
        Api.Data.courseShallowDecoder
