{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Course exposing
    ( courseBulkSetActivities
    , courseCreate
    , courseDelete
    , courseEnrollmentCreate
    , courseEnrollmentDelete
    , courseEnrollmentList
    , courseEnrollmentPartialUpdate
    , courseEnrollmentRead
    , courseEnrollmentUpdate
    , courseList
    , coursePartialUpdate
    , courseRead
    , courseUpdate
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


courseBulkSetActivities : String -> Api.Data.BulkSetActivities -> Api.Request ()
courseBulkSetActivities id_path data_body =
    Api.request
        "POST"
        "/course/{id}/bulk_set_activities/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeBulkSetActivities data_body))
        (Json.Decode.succeed ())


courseCreate : Api.Data.Course -> Api.Request Api.Data.Course
courseCreate data_body =
    Api.request
        "POST"
        "/course/"
        []
        []
        []
        (Just (Api.Data.encodeCourse data_body))
        Api.Data.courseDecoder


courseDelete : String -> Api.Request ()
courseDelete id_path =
    Api.request
        "DELETE"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


courseEnrollmentCreate : Api.Data.CourseEnrollmentWrite -> Api.Request Api.Data.CourseEnrollmentWrite
courseEnrollmentCreate data_body =
    Api.request
        "POST"
        "/course/enrollment/"
        []
        []
        []
        (Just (Api.Data.encodeCourseEnrollmentWrite data_body))
        Api.Data.courseEnrollmentWriteDecoder


courseEnrollmentDelete : String -> Api.Request ()
courseEnrollmentDelete id_path =
    Api.request
        "DELETE"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


courseEnrollmentList : Api.Request (List Api.Data.CourseEnrollmentRead)
courseEnrollmentList =
    Api.request
        "GET"
        "/course/enrollment/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.courseEnrollmentReadDecoder)


courseEnrollmentPartialUpdate : String -> Api.Data.CourseEnrollmentRead -> Api.Request Api.Data.CourseEnrollmentRead
courseEnrollmentPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourseEnrollmentRead data_body))
        Api.Data.courseEnrollmentReadDecoder


courseEnrollmentRead : String -> Api.Request Api.Data.CourseEnrollmentRead
courseEnrollmentRead id_path =
    Api.request
        "GET"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.courseEnrollmentReadDecoder


courseEnrollmentUpdate : String -> Api.Data.CourseEnrollmentWrite -> Api.Request Api.Data.CourseEnrollmentWrite
courseEnrollmentUpdate id_path data_body =
    Api.request
        "PUT"
        "/course/enrollment/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourseEnrollmentWrite data_body))
        Api.Data.courseEnrollmentWriteDecoder


courseList : Api.Request (List Api.Data.Course)
courseList =
    Api.request
        "GET"
        "/course/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.courseDecoder)


coursePartialUpdate : String -> Api.Data.Course -> Api.Request Api.Data.Course
coursePartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourse data_body))
        Api.Data.courseDecoder


courseRead : String -> Api.Request Api.Data.Course
courseRead id_path =
    Api.request
        "GET"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.courseDecoder


courseUpdate : String -> Api.Data.Course -> Api.Request Api.Data.Course
courseUpdate id_path data_body =
    Api.request
        "PUT"
        "/course/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeCourse data_body))
        Api.Data.courseDecoder
