{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Download exposing (download)

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


download : String -> String -> Api.Request Api.Data.File
download id_path filename_path =
    Api.request
        "GET"
        "/file/{id}/{filename}/"
        [ ( "id", identity id_path ), ( "filename", identity filename_path ) ]
        []
        []
        Nothing
        Api.Data.fileDecoder
