{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.File exposing
    ( fileCreate
    , fileDelete
    , fileList
    , filePartialUpdate
    , fileRead
    , fileUpdate
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


fileCreate : Api.Data.File -> Api.Request Api.Data.File
fileCreate data_body =
    Api.request
        "POST"
        "/file/"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeFile data_body)))
        Api.Data.fileDecoder


fileDelete : String -> Api.Request ()
fileDelete id_path =
    Api.request
        "DELETE"
        "/file/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


fileList : Api.Request (List Api.Data.File)
fileList =
    Api.request
        "GET"
        "/file/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.fileDecoder)


filePartialUpdate : String -> Api.Data.File -> Api.Request Api.Data.File
filePartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/file/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeFile data_body)))
        Api.Data.fileDecoder


fileRead : String -> Api.Request Api.Data.File
fileRead id_path =
    Api.request
        "GET"
        "/file/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.fileDecoder


fileUpdate : String -> Api.Data.File -> Api.Request Api.Data.File
fileUpdate id_path data_body =
    Api.request
        "PUT"
        "/file/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeFile data_body)))
        Api.Data.fileDecoder
