{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Mark exposing
    ( markCreate
    , markDelete
    , markExport
    , markList
    , markPartialUpdate
    , markRead
    , markUpdate
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


markCreate : Api.Data.Mark -> Api.Request Api.Data.Mark
markCreate data_body =
    Api.request
        "POST"
        "/mark/"
        []
        []
        []
        (Just (Api.Data.encodeMark data_body))
        Api.Data.markDecoder


markDelete : String -> Api.Request ()
markDelete id_path =
    Api.request
        "DELETE"
        "/mark/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


markExport : Api.Request (List Api.Data.Mark)
markExport =
    Api.request
        "GET"
        "/mark/export/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.markDecoder)


markList : Api.Request (List Api.Data.Mark)
markList =
    Api.request
        "GET"
        "/mark/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.markDecoder)


markPartialUpdate : String -> Api.Data.Mark -> Api.Request Api.Data.Mark
markPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/mark/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeMark data_body))
        Api.Data.markDecoder


markRead : String -> Api.Request Api.Data.Mark
markRead id_path =
    Api.request
        "GET"
        "/mark/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.markDecoder


markUpdate : String -> Api.Data.Mark -> Api.Request Api.Data.Mark
markUpdate id_path data_body =
    Api.request
        "PUT"
        "/mark/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeMark data_body))
        Api.Data.markDecoder
