{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Message exposing
    ( messageCreate
    , messageDelete
    , messageList
    , messagePartialUpdate
    , messageRead
    , messageUpdate
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


messageCreate : Api.Data.Message -> Api.Request Api.Data.Message
messageCreate data_body =
    Api.request
        "POST"
        "/message/"
        []
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeMessage data_body)))
        Api.Data.messageDecoder


messageDelete : String -> Api.Request ()
messageDelete id_path =
    Api.request
        "DELETE"
        "/message/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


messageList : Api.Request (List Api.Data.Message)
messageList =
    Api.request
        "GET"
        "/message/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.messageDecoder)


messagePartialUpdate : String -> Api.Data.Message -> Api.Request Api.Data.Message
messagePartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/message/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeMessage data_body)))
        Api.Data.messageDecoder


messageRead : String -> Api.Request Api.Data.Message
messageRead id_path =
    Api.request
        "GET"
        "/message/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.messageDecoder


messageUpdate : String -> Api.Data.Message -> Api.Request Api.Data.Message
messageUpdate id_path data_body =
    Api.request
        "PUT"
        "/message/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Maybe.map Http.jsonBody (Just (Api.Data.encodeMessage data_body)))
        Api.Data.messageDecoder
