{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Olympiad exposing
    ( olympiadCreate
    , olympiadDelete
    , olympiadList
    , olympiadPartialUpdate
    , olympiadParticipationCreate
    , olympiadParticipationDelete
    , olympiadParticipationList
    , olympiadParticipationPartialUpdate
    , olympiadParticipationRead
    , olympiadParticipationUpdate
    , olympiadRead
    , olympiadUpdate
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


olympiadCreate : Api.Data.Olympiad -> Api.Request Api.Data.Olympiad
olympiadCreate data_body =
    Api.request
        "POST"
        "/olympiad/"
        []
        []
        []
        (Just (Api.Data.encodeOlympiad data_body))
        Api.Data.olympiadDecoder


olympiadDelete : String -> Api.Request ()
olympiadDelete id_path =
    Api.request
        "DELETE"
        "/olympiad/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


olympiadList : Api.Request (List Api.Data.Olympiad)
olympiadList =
    Api.request
        "GET"
        "/olympiad/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.olympiadDecoder)


olympiadPartialUpdate : String -> Api.Data.Olympiad -> Api.Request Api.Data.Olympiad
olympiadPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/olympiad/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeOlympiad data_body))
        Api.Data.olympiadDecoder


olympiadParticipationCreate : Api.Data.OlympiadParticipation -> Api.Request Api.Data.OlympiadParticipation
olympiadParticipationCreate data_body =
    Api.request
        "POST"
        "/olympiad/participation/"
        []
        []
        []
        (Just (Api.Data.encodeOlympiadParticipation data_body))
        Api.Data.olympiadParticipationDecoder


olympiadParticipationDelete : String -> Api.Request ()
olympiadParticipationDelete id_path =
    Api.request
        "DELETE"
        "/olympiad/participation/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        (Json.Decode.succeed ())


olympiadParticipationList : Api.Request (List Api.Data.OlympiadParticipation)
olympiadParticipationList =
    Api.request
        "GET"
        "/olympiad/participation/"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.olympiadParticipationDecoder)


olympiadParticipationPartialUpdate : String -> Api.Data.OlympiadParticipation -> Api.Request Api.Data.OlympiadParticipation
olympiadParticipationPartialUpdate id_path data_body =
    Api.request
        "PATCH"
        "/olympiad/participation/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeOlympiadParticipation data_body))
        Api.Data.olympiadParticipationDecoder


olympiadParticipationRead : String -> Api.Request Api.Data.OlympiadParticipation
olympiadParticipationRead id_path =
    Api.request
        "GET"
        "/olympiad/participation/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.olympiadParticipationDecoder


olympiadParticipationUpdate : String -> Api.Data.OlympiadParticipation -> Api.Request Api.Data.OlympiadParticipation
olympiadParticipationUpdate id_path data_body =
    Api.request
        "PUT"
        "/olympiad/participation/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeOlympiadParticipation data_body))
        Api.Data.olympiadParticipationDecoder


olympiadRead : String -> Api.Request Api.Data.Olympiad
olympiadRead id_path =
    Api.request
        "GET"
        "/olympiad/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        Nothing
        Api.Data.olympiadDecoder


olympiadUpdate : String -> Api.Data.Olympiad -> Api.Request Api.Data.Olympiad
olympiadUpdate id_path data_body =
    Api.request
        "PUT"
        "/olympiad/{id}/"
        [ ( "id", identity id_path ) ]
        []
        []
        (Just (Api.Data.encodeOlympiad data_body))
        Api.Data.olympiadDecoder
