{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Stats exposing (statsCounters)

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode


statsCounters : Api.Request Api.Data.Counters
statsCounters =
    Api.request
        "GET"
        "/stats/counters/"
        []
        []
        []
        Nothing
        Api.Data.countersDecoder
