stages:
  - tools
  - build
  - test
  - push
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

after_script:
  - docker logout $CI_REGISTRY || true

build-image:
  stage: build
  tags: 
    - bare
  script:
    - env
    - docker build -t git.lnmo.ru/lcme/edu-lnmo-front-builder:latest .

deploy-2-production:
  stage: deploy
  tags:
    - bare
  script:
    - docker run -v /var/www/edu-lnmo-ru:/build_out git.lnmo.ru/lcme/edu-lnmo-front-builder:latest ./build_production.sh
  environment:
    name: production
    url: https://edu.lnmo.ru
  when: manual
