{-
   LCME EDU API
   ...

   The version of the OpenAPI document: v1
   Contact: sysadmin@lnmo.ru

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Data exposing
    ( Activity, ActivityType(..), activityTypeVariants
    , Course
    , CourseEnrollment, CourseEnrollmentRole(..), courseEnrollmentRoleVariants
    , Department
    , Education
    , EducationSpecialization
    , File
    , Login
    , Mark, MarkFinalType(..), markFinalTypeVariants
    , Message
    , MessageNews
    , MessagePrivate
    , MessageTaskSubmission
    , Organization
    , SetPassword
    , Token
    , UnreadObject, UnreadObjectType(..), unreadObjectTypeVariants
    , User
    , encodeActivity
    , encodeCourse
    , encodeCourseEnrollment
    , encodeDepartment
    , encodeEducation
    , encodeEducationSpecialization
    , encodeFile
    , encodeLogin
    , encodeMark
    , encodeMessage
    , encodeMessageNews
    , encodeMessagePrivate
    , encodeMessageTaskSubmission
    , encodeOrganization
    , encodeSetPassword
    , encodeToken
    , encodeUnreadObject
    , encodeUser
    , activityDecoder
    , courseDecoder
    , courseEnrollmentDecoder
    , departmentDecoder
    , educationDecoder
    , educationSpecializationDecoder
    , fileDecoder
    , loginDecoder
    , markDecoder
    , messageDecoder
    , messageNewsDecoder
    , messagePrivateDecoder
    , messageTaskSubmissionDecoder
    , organizationDecoder
    , setPasswordDecoder
    , tokenDecoder
    , unreadObjectDecoder
    , userDecoder
    )

import Api
import Api.Time exposing (Posix)
import Dict
import Json.Decode
import Json.Encode
import Uuid exposing (Uuid)


-- MODEL


type alias Activity =
    { id : Maybe Uuid
    , type_ : Maybe ActivityType
    , title : String
    , keywords : Maybe String
    , isHidden : Maybe Bool
    , marksLimit : Maybe Int
    , order : Int
    , date : Maybe Posix
    , group : Maybe String
    , body : Maybe String
    , dueDate : Maybe Posix
    , link : Maybe String
    , embed : Maybe Bool
    , course : Uuid
    , files : Maybe (List (Uuid))
    }


type ActivityType
    = ActivityTypeGEN
    | ActivityTypeART
    | ActivityTypeTSK
    | ActivityTypeLNK
    | ActivityTypeMED


activityTypeVariants : List ActivityType
activityTypeVariants =
    [ ActivityTypeGEN
    , ActivityTypeART
    , ActivityTypeTSK
    , ActivityTypeLNK
    , ActivityTypeMED
    ]


type alias Course =
    { id : Maybe Uuid
    , forSpecialization : EducationSpecialization
    , logo : File
    , cover : File
    , title : String
    , description : String
    , forClass : Maybe String
    , forGroup : Maybe String
    }


type alias CourseEnrollment =
    { id : Maybe Uuid
    , role : CourseEnrollmentRole
    , finishedOn : Maybe Posix
    , person : Uuid
    , course : Uuid
    }


type CourseEnrollmentRole
    = CourseEnrollmentRoleT
    | CourseEnrollmentRoleS


courseEnrollmentRoleVariants : List CourseEnrollmentRole
courseEnrollmentRoleVariants =
    [ CourseEnrollmentRoleT
    , CourseEnrollmentRoleS
    ]


type alias Department =
    { id : Maybe Uuid
    , name : String
    , organization : Uuid
    }


type alias Education =
    { id : Maybe Uuid
    , started : Posix
    , finished : Maybe Posix
    , startingClass : String
    , finishingClass : Maybe String
    , student : Uuid
    , specialization : Uuid
    }


type alias EducationSpecialization =
    { id : Maybe Uuid
    , name : String
    , department : Uuid
    }


type alias File =
    { id : Maybe Uuid
    , name : String
    , hash : String
    , size : Int
    , mimeType : String
    }


type alias Login =
    { username : String
    , password : String
    }


type alias Mark =
    { id : Maybe Uuid
    , value : String
    , comment : Maybe String
    , finalType : Maybe MarkFinalType
    , teacher : Uuid
    , student : Uuid
    , activity : Uuid
    , course : Uuid
    }


type MarkFinalType
    = MarkFinalTypeQ1
    | MarkFinalTypeQ2
    | MarkFinalTypeQ3
    | MarkFinalTypeQ4
    | MarkFinalTypeH1
    | MarkFinalTypeH2
    | MarkFinalTypeY
    | MarkFinalTypeE
    | MarkFinalTypeF


markFinalTypeVariants : List MarkFinalType
markFinalTypeVariants =
    [ MarkFinalTypeQ1
    , MarkFinalTypeQ2
    , MarkFinalTypeQ3
    , MarkFinalTypeQ4
    , MarkFinalTypeH1
    , MarkFinalTypeH2
    , MarkFinalTypeY
    , MarkFinalTypeE
    , MarkFinalTypeF
    ]


type alias Message =
    { id : Maybe Uuid
    , body : Maybe String
    , sentAt : Posix
    , sender : Uuid
    , attachments : Maybe (List (Uuid))
    }


type alias MessageNews =
    { id : Maybe Uuid
    , body : Maybe String
    , sentAt : Posix
    , sender : Uuid
    , attachments : Maybe (List (Uuid))
    }


type alias MessagePrivate =
    { id : Maybe Uuid
    , body : Maybe String
    , sentAt : Posix
    , sender : Uuid
    , receiver : Uuid
    , attachments : Maybe (List (Uuid))
    }


type alias MessageTaskSubmission =
    { id : Maybe Uuid
    , body : Maybe String
    , sentAt : Posix
    , sender : Uuid
    , receiver : Uuid
    , activity : Uuid
    , attachments : Maybe (List (Uuid))
    }


type alias Organization =
    { id : Maybe Uuid
    , name : String
    , nameShort : Maybe String
    }


type alias SetPassword =
    { password : String
    }


type alias Token =
    { user : User
    , key : String
    }


type alias UnreadObject =
    { id : Maybe Uuid
    , obj : Uuid
    , type_ : Maybe UnreadObjectType
    , created : Posix
    , user : Uuid
    }


type UnreadObjectType
    = UnreadObjectTypeMSG
    | UnreadObjectTypeMRK
    | UnreadObjectTypeCRS
    | UnreadObjectTypeACT
    | UnreadObjectTypeNWS
    | UnreadObjectTypeEDU
    | UnreadObjectTypeFLE
    | UnreadObjectTypeFRM
    | UnreadObjectTypeTSK
    | UnreadObjectTypeUNK


unreadObjectTypeVariants : List UnreadObjectType
unreadObjectTypeVariants =
    [ UnreadObjectTypeMSG
    , UnreadObjectTypeMRK
    , UnreadObjectTypeCRS
    , UnreadObjectTypeACT
    , UnreadObjectTypeNWS
    , UnreadObjectTypeEDU
    , UnreadObjectTypeFLE
    , UnreadObjectTypeFRM
    , UnreadObjectTypeTSK
    , UnreadObjectTypeUNK
    ]


type alias User =
    { id : Maybe Uuid
    , lastLogin : Maybe Posix
    , isSuperuser : Maybe Bool
    , username : String
    , firstName : Maybe String
    , lastName : Maybe String
    , email : Maybe String
    , isStaff : Maybe Bool
    , isActive : Maybe Bool
    , dateJoined : Maybe Posix
    , middleName : Maybe String
    , birthDate : Maybe Posix
    , avatar : Maybe String
    , groups : Maybe (List (Int))
    , userPermissions : Maybe (List (Int))
    , children : Maybe (List (Uuid))
    }


-- ENCODER


encodeActivity : Activity -> Json.Encode.Value
encodeActivity =
    encodeObject << encodeActivityPairs


encodeActivityWithTag : ( String, String ) -> Activity -> Json.Encode.Value
encodeActivityWithTag (tagField, tag) model =
    encodeObject (encodeActivityPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeActivityPairs : Activity -> List EncodedField
encodeActivityPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , maybeEncode "type" encodeActivityType model.type_
            , encode "title" Json.Encode.string model.title
            , maybeEncode "keywords" Json.Encode.string model.keywords
            , maybeEncode "is_hidden" Json.Encode.bool model.isHidden
            , maybeEncode "marks_limit" Json.Encode.int model.marksLimit
            , encode "order" Json.Encode.int model.order
            , maybeEncodeNullable "date" Api.Time.encodeDate model.date
            , maybeEncodeNullable "group" Json.Encode.string model.group
            , maybeEncode "body" Json.Encode.string model.body
            , maybeEncodeNullable "due_date" Api.Time.encodeDateTime model.dueDate
            , maybeEncodeNullable "link" Json.Encode.string model.link
            , maybeEncode "embed" Json.Encode.bool model.embed
            , encode "course" Uuid.encode model.course
            , maybeEncode "files" (Json.Encode.list Uuid.encode) model.files
            ]
    in
    pairs

stringFromActivityType : ActivityType -> String
stringFromActivityType model =
    case model of
        ActivityTypeGEN ->
            "GEN"

        ActivityTypeART ->
            "ART"

        ActivityTypeTSK ->
            "TSK"

        ActivityTypeLNK ->
            "LNK"

        ActivityTypeMED ->
            "MED"


encodeActivityType : ActivityType -> Json.Encode.Value
encodeActivityType =
    Json.Encode.string << stringFromActivityType



encodeCourse : Course -> Json.Encode.Value
encodeCourse =
    encodeObject << encodeCoursePairs


encodeCourseWithTag : ( String, String ) -> Course -> Json.Encode.Value
encodeCourseWithTag (tagField, tag) model =
    encodeObject (encodeCoursePairs model ++ [ encode tagField Json.Encode.string tag ])


encodeCoursePairs : Course -> List EncodedField
encodeCoursePairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "for_specialization" encodeEducationSpecialization model.forSpecialization
            , encode "logo" encodeFile model.logo
            , encode "cover" encodeFile model.cover
            , encode "title" Json.Encode.string model.title
            , encode "description" Json.Encode.string model.description
            , maybeEncode "for_class" Json.Encode.string model.forClass
            , maybeEncodeNullable "for_group" Json.Encode.string model.forGroup
            ]
    in
    pairs


encodeCourseEnrollment : CourseEnrollment -> Json.Encode.Value
encodeCourseEnrollment =
    encodeObject << encodeCourseEnrollmentPairs


encodeCourseEnrollmentWithTag : ( String, String ) -> CourseEnrollment -> Json.Encode.Value
encodeCourseEnrollmentWithTag (tagField, tag) model =
    encodeObject (encodeCourseEnrollmentPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeCourseEnrollmentPairs : CourseEnrollment -> List EncodedField
encodeCourseEnrollmentPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "role" encodeCourseEnrollmentRole model.role
            , maybeEncodeNullable "finished_on" Api.Time.encodeDateTime model.finishedOn
            , encode "person" Uuid.encode model.person
            , encode "course" Uuid.encode model.course
            ]
    in
    pairs

stringFromCourseEnrollmentRole : CourseEnrollmentRole -> String
stringFromCourseEnrollmentRole model =
    case model of
        CourseEnrollmentRoleT ->
            "t"

        CourseEnrollmentRoleS ->
            "s"


encodeCourseEnrollmentRole : CourseEnrollmentRole -> Json.Encode.Value
encodeCourseEnrollmentRole =
    Json.Encode.string << stringFromCourseEnrollmentRole



encodeDepartment : Department -> Json.Encode.Value
encodeDepartment =
    encodeObject << encodeDepartmentPairs


encodeDepartmentWithTag : ( String, String ) -> Department -> Json.Encode.Value
encodeDepartmentWithTag (tagField, tag) model =
    encodeObject (encodeDepartmentPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeDepartmentPairs : Department -> List EncodedField
encodeDepartmentPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "name" Json.Encode.string model.name
            , encode "organization" Uuid.encode model.organization
            ]
    in
    pairs


encodeEducation : Education -> Json.Encode.Value
encodeEducation =
    encodeObject << encodeEducationPairs


encodeEducationWithTag : ( String, String ) -> Education -> Json.Encode.Value
encodeEducationWithTag (tagField, tag) model =
    encodeObject (encodeEducationPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeEducationPairs : Education -> List EncodedField
encodeEducationPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "started" Api.Time.encodeDate model.started
            , maybeEncodeNullable "finished" Api.Time.encodeDate model.finished
            , encode "starting_class" Json.Encode.string model.startingClass
            , maybeEncodeNullable "finishing_class" Json.Encode.string model.finishingClass
            , encode "student" Uuid.encode model.student
            , encode "specialization" Uuid.encode model.specialization
            ]
    in
    pairs


encodeEducationSpecialization : EducationSpecialization -> Json.Encode.Value
encodeEducationSpecialization =
    encodeObject << encodeEducationSpecializationPairs


encodeEducationSpecializationWithTag : ( String, String ) -> EducationSpecialization -> Json.Encode.Value
encodeEducationSpecializationWithTag (tagField, tag) model =
    encodeObject (encodeEducationSpecializationPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeEducationSpecializationPairs : EducationSpecialization -> List EncodedField
encodeEducationSpecializationPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "name" Json.Encode.string model.name
            , encode "department" Uuid.encode model.department
            ]
    in
    pairs


encodeFile : File -> Json.Encode.Value
encodeFile =
    encodeObject << encodeFilePairs


encodeFileWithTag : ( String, String ) -> File -> Json.Encode.Value
encodeFileWithTag (tagField, tag) model =
    encodeObject (encodeFilePairs model ++ [ encode tagField Json.Encode.string tag ])


encodeFilePairs : File -> List EncodedField
encodeFilePairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "name" Json.Encode.string model.name
            , encode "hash" Json.Encode.string model.hash
            , encode "size" Json.Encode.int model.size
            , encode "mime_type" Json.Encode.string model.mimeType
            ]
    in
    pairs


encodeLogin : Login -> Json.Encode.Value
encodeLogin =
    encodeObject << encodeLoginPairs


encodeLoginWithTag : ( String, String ) -> Login -> Json.Encode.Value
encodeLoginWithTag (tagField, tag) model =
    encodeObject (encodeLoginPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeLoginPairs : Login -> List EncodedField
encodeLoginPairs model =
    let
        pairs =
            [ encode "username" Json.Encode.string model.username
            , encode "password" Json.Encode.string model.password
            ]
    in
    pairs


encodeMark : Mark -> Json.Encode.Value
encodeMark =
    encodeObject << encodeMarkPairs


encodeMarkWithTag : ( String, String ) -> Mark -> Json.Encode.Value
encodeMarkWithTag (tagField, tag) model =
    encodeObject (encodeMarkPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeMarkPairs : Mark -> List EncodedField
encodeMarkPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "value" Json.Encode.string model.value
            , maybeEncode "comment" Json.Encode.string model.comment
            , maybeEncodeNullable "final_type" encodeMarkFinalType model.finalType
            , encode "teacher" Uuid.encode model.teacher
            , encode "student" Uuid.encode model.student
            , encode "activity" Uuid.encode model.activity
            , encode "course" Uuid.encode model.course
            ]
    in
    pairs

stringFromMarkFinalType : MarkFinalType -> String
stringFromMarkFinalType model =
    case model of
        MarkFinalTypeQ1 ->
            "Q1"

        MarkFinalTypeQ2 ->
            "Q2"

        MarkFinalTypeQ3 ->
            "Q3"

        MarkFinalTypeQ4 ->
            "Q4"

        MarkFinalTypeH1 ->
            "H1"

        MarkFinalTypeH2 ->
            "H2"

        MarkFinalTypeY ->
            "Y"

        MarkFinalTypeE ->
            "E"

        MarkFinalTypeF ->
            "F"


encodeMarkFinalType : MarkFinalType -> Json.Encode.Value
encodeMarkFinalType =
    Json.Encode.string << stringFromMarkFinalType



encodeMessage : Message -> Json.Encode.Value
encodeMessage =
    encodeObject << encodeMessagePairs


encodeMessageWithTag : ( String, String ) -> Message -> Json.Encode.Value
encodeMessageWithTag (tagField, tag) model =
    encodeObject (encodeMessagePairs model ++ [ encode tagField Json.Encode.string tag ])


encodeMessagePairs : Message -> List EncodedField
encodeMessagePairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , maybeEncode "body" Json.Encode.string model.body
            , encode "sent_at" Api.Time.encodeDateTime model.sentAt
            , encode "sender" Uuid.encode model.sender
            , maybeEncode "attachments" (Json.Encode.list Uuid.encode) model.attachments
            ]
    in
    pairs


encodeMessageNews : MessageNews -> Json.Encode.Value
encodeMessageNews =
    encodeObject << encodeMessageNewsPairs


encodeMessageNewsWithTag : ( String, String ) -> MessageNews -> Json.Encode.Value
encodeMessageNewsWithTag (tagField, tag) model =
    encodeObject (encodeMessageNewsPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeMessageNewsPairs : MessageNews -> List EncodedField
encodeMessageNewsPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , maybeEncode "body" Json.Encode.string model.body
            , encode "sent_at" Api.Time.encodeDateTime model.sentAt
            , encode "sender" Uuid.encode model.sender
            , maybeEncode "attachments" (Json.Encode.list Uuid.encode) model.attachments
            ]
    in
    pairs


encodeMessagePrivate : MessagePrivate -> Json.Encode.Value
encodeMessagePrivate =
    encodeObject << encodeMessagePrivatePairs


encodeMessagePrivateWithTag : ( String, String ) -> MessagePrivate -> Json.Encode.Value
encodeMessagePrivateWithTag (tagField, tag) model =
    encodeObject (encodeMessagePrivatePairs model ++ [ encode tagField Json.Encode.string tag ])


encodeMessagePrivatePairs : MessagePrivate -> List EncodedField
encodeMessagePrivatePairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , maybeEncode "body" Json.Encode.string model.body
            , encode "sent_at" Api.Time.encodeDateTime model.sentAt
            , encode "sender" Uuid.encode model.sender
            , encode "receiver" Uuid.encode model.receiver
            , maybeEncode "attachments" (Json.Encode.list Uuid.encode) model.attachments
            ]
    in
    pairs


encodeMessageTaskSubmission : MessageTaskSubmission -> Json.Encode.Value
encodeMessageTaskSubmission =
    encodeObject << encodeMessageTaskSubmissionPairs


encodeMessageTaskSubmissionWithTag : ( String, String ) -> MessageTaskSubmission -> Json.Encode.Value
encodeMessageTaskSubmissionWithTag (tagField, tag) model =
    encodeObject (encodeMessageTaskSubmissionPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeMessageTaskSubmissionPairs : MessageTaskSubmission -> List EncodedField
encodeMessageTaskSubmissionPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , maybeEncode "body" Json.Encode.string model.body
            , encode "sent_at" Api.Time.encodeDateTime model.sentAt
            , encode "sender" Uuid.encode model.sender
            , encode "receiver" Uuid.encode model.receiver
            , encode "activity" Uuid.encode model.activity
            , maybeEncode "attachments" (Json.Encode.list Uuid.encode) model.attachments
            ]
    in
    pairs


encodeOrganization : Organization -> Json.Encode.Value
encodeOrganization =
    encodeObject << encodeOrganizationPairs


encodeOrganizationWithTag : ( String, String ) -> Organization -> Json.Encode.Value
encodeOrganizationWithTag (tagField, tag) model =
    encodeObject (encodeOrganizationPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeOrganizationPairs : Organization -> List EncodedField
encodeOrganizationPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "name" Json.Encode.string model.name
            , maybeEncodeNullable "name_short" Json.Encode.string model.nameShort
            ]
    in
    pairs


encodeSetPassword : SetPassword -> Json.Encode.Value
encodeSetPassword =
    encodeObject << encodeSetPasswordPairs


encodeSetPasswordWithTag : ( String, String ) -> SetPassword -> Json.Encode.Value
encodeSetPasswordWithTag (tagField, tag) model =
    encodeObject (encodeSetPasswordPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeSetPasswordPairs : SetPassword -> List EncodedField
encodeSetPasswordPairs model =
    let
        pairs =
            [ encode "password" Json.Encode.string model.password
            ]
    in
    pairs


encodeToken : Token -> Json.Encode.Value
encodeToken =
    encodeObject << encodeTokenPairs


encodeTokenWithTag : ( String, String ) -> Token -> Json.Encode.Value
encodeTokenWithTag (tagField, tag) model =
    encodeObject (encodeTokenPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeTokenPairs : Token -> List EncodedField
encodeTokenPairs model =
    let
        pairs =
            [ encode "user" encodeUser model.user
            , encode "key" Json.Encode.string model.key
            ]
    in
    pairs


encodeUnreadObject : UnreadObject -> Json.Encode.Value
encodeUnreadObject =
    encodeObject << encodeUnreadObjectPairs


encodeUnreadObjectWithTag : ( String, String ) -> UnreadObject -> Json.Encode.Value
encodeUnreadObjectWithTag (tagField, tag) model =
    encodeObject (encodeUnreadObjectPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeUnreadObjectPairs : UnreadObject -> List EncodedField
encodeUnreadObjectPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , encode "obj" Uuid.encode model.obj
            , maybeEncode "type" encodeUnreadObjectType model.type_
            , encode "created" Api.Time.encodeDateTime model.created
            , encode "user" Uuid.encode model.user
            ]
    in
    pairs

stringFromUnreadObjectType : UnreadObjectType -> String
stringFromUnreadObjectType model =
    case model of
        UnreadObjectTypeMSG ->
            "MSG"

        UnreadObjectTypeMRK ->
            "MRK"

        UnreadObjectTypeCRS ->
            "CRS"

        UnreadObjectTypeACT ->
            "ACT"

        UnreadObjectTypeNWS ->
            "NWS"

        UnreadObjectTypeEDU ->
            "EDU"

        UnreadObjectTypeFLE ->
            "FLE"

        UnreadObjectTypeFRM ->
            "FRM"

        UnreadObjectTypeTSK ->
            "TSK"

        UnreadObjectTypeUNK ->
            "UNK"


encodeUnreadObjectType : UnreadObjectType -> Json.Encode.Value
encodeUnreadObjectType =
    Json.Encode.string << stringFromUnreadObjectType



encodeUser : User -> Json.Encode.Value
encodeUser =
    encodeObject << encodeUserPairs


encodeUserWithTag : ( String, String ) -> User -> Json.Encode.Value
encodeUserWithTag (tagField, tag) model =
    encodeObject (encodeUserPairs model ++ [ encode tagField Json.Encode.string tag ])


encodeUserPairs : User -> List EncodedField
encodeUserPairs model =
    let
        pairs =
            [ maybeEncode "id" Uuid.encode model.id
            , maybeEncodeNullable "last_login" Api.Time.encodeDateTime model.lastLogin
            , maybeEncode "is_superuser" Json.Encode.bool model.isSuperuser
            , encode "username" Json.Encode.string model.username
            , maybeEncode "first_name" Json.Encode.string model.firstName
            , maybeEncode "last_name" Json.Encode.string model.lastName
            , maybeEncode "email" Json.Encode.string model.email
            , maybeEncode "is_staff" Json.Encode.bool model.isStaff
            , maybeEncode "is_active" Json.Encode.bool model.isActive
            , maybeEncode "date_joined" Api.Time.encodeDateTime model.dateJoined
            , maybeEncodeNullable "middle_name" Json.Encode.string model.middleName
            , maybeEncodeNullable "birth_date" Api.Time.encodeDate model.birthDate
            , maybeEncodeNullable "avatar" Json.Encode.string model.avatar
            , maybeEncode "groups" (Json.Encode.list Json.Encode.int) model.groups
            , maybeEncode "user_permissions" (Json.Encode.list Json.Encode.int) model.userPermissions
            , maybeEncode "children" (Json.Encode.list Uuid.encode) model.children
            ]
    in
    pairs


-- DECODER


activityDecoder : Json.Decode.Decoder Activity
activityDecoder =
    Json.Decode.succeed Activity
        |> maybeDecode "id" Uuid.decoder Nothing
        |> maybeDecode "type" activityTypeDecoder Nothing
        |> decode "title" Json.Decode.string 
        |> maybeDecode "keywords" Json.Decode.string Nothing
        |> maybeDecode "is_hidden" Json.Decode.bool Nothing
        |> maybeDecode "marks_limit" Json.Decode.int Nothing
        |> decode "order" Json.Decode.int 
        |> maybeDecodeNullable "date" Api.Time.dateDecoder Nothing
        |> maybeDecodeNullable "group" Json.Decode.string Nothing
        |> maybeDecode "body" Json.Decode.string Nothing
        |> maybeDecodeNullable "due_date" Api.Time.dateTimeDecoder Nothing
        |> maybeDecodeNullable "link" Json.Decode.string Nothing
        |> maybeDecode "embed" Json.Decode.bool Nothing
        |> decode "course" Uuid.decoder 
        |> maybeDecode "files" (Json.Decode.list Uuid.decoder) Nothing


activityTypeDecoder : Json.Decode.Decoder ActivityType
activityTypeDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "GEN" ->
                        Json.Decode.succeed ActivityTypeGEN

                    "ART" ->
                        Json.Decode.succeed ActivityTypeART

                    "TSK" ->
                        Json.Decode.succeed ActivityTypeTSK

                    "LNK" ->
                        Json.Decode.succeed ActivityTypeLNK

                    "MED" ->
                        Json.Decode.succeed ActivityTypeMED

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



courseDecoder : Json.Decode.Decoder Course
courseDecoder =
    Json.Decode.succeed Course
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "for_specialization" educationSpecializationDecoder 
        |> decode "logo" fileDecoder 
        |> decode "cover" fileDecoder 
        |> decode "title" Json.Decode.string 
        |> decode "description" Json.Decode.string 
        |> maybeDecode "for_class" Json.Decode.string Nothing
        |> maybeDecodeNullable "for_group" Json.Decode.string Nothing


courseEnrollmentDecoder : Json.Decode.Decoder CourseEnrollment
courseEnrollmentDecoder =
    Json.Decode.succeed CourseEnrollment
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "role" courseEnrollmentRoleDecoder 
        |> maybeDecodeNullable "finished_on" Api.Time.dateTimeDecoder Nothing
        |> decode "person" Uuid.decoder 
        |> decode "course" Uuid.decoder 


courseEnrollmentRoleDecoder : Json.Decode.Decoder CourseEnrollmentRole
courseEnrollmentRoleDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "t" ->
                        Json.Decode.succeed CourseEnrollmentRoleT

                    "s" ->
                        Json.Decode.succeed CourseEnrollmentRoleS

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



departmentDecoder : Json.Decode.Decoder Department
departmentDecoder =
    Json.Decode.succeed Department
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "name" Json.Decode.string 
        |> decode "organization" Uuid.decoder 


educationDecoder : Json.Decode.Decoder Education
educationDecoder =
    Json.Decode.succeed Education
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "started" Api.Time.dateDecoder 
        |> maybeDecodeNullable "finished" Api.Time.dateDecoder Nothing
        |> decode "starting_class" Json.Decode.string 
        |> maybeDecodeNullable "finishing_class" Json.Decode.string Nothing
        |> decode "student" Uuid.decoder 
        |> decode "specialization" Uuid.decoder 


educationSpecializationDecoder : Json.Decode.Decoder EducationSpecialization
educationSpecializationDecoder =
    Json.Decode.succeed EducationSpecialization
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "name" Json.Decode.string 
        |> decode "department" Uuid.decoder 


fileDecoder : Json.Decode.Decoder File
fileDecoder =
    Json.Decode.succeed File
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "name" Json.Decode.string 
        |> decode "hash" Json.Decode.string 
        |> decode "size" Json.Decode.int 
        |> decode "mime_type" Json.Decode.string 


loginDecoder : Json.Decode.Decoder Login
loginDecoder =
    Json.Decode.succeed Login
        |> decode "username" Json.Decode.string 
        |> decode "password" Json.Decode.string 


markDecoder : Json.Decode.Decoder Mark
markDecoder =
    Json.Decode.succeed Mark
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "value" Json.Decode.string 
        |> maybeDecode "comment" Json.Decode.string Nothing
        |> maybeDecodeNullable "final_type" markFinalTypeDecoder Nothing
        |> decode "teacher" Uuid.decoder 
        |> decode "student" Uuid.decoder 
        |> decode "activity" Uuid.decoder 
        |> decode "course" Uuid.decoder 


markFinalTypeDecoder : Json.Decode.Decoder MarkFinalType
markFinalTypeDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "Q1" ->
                        Json.Decode.succeed MarkFinalTypeQ1

                    "Q2" ->
                        Json.Decode.succeed MarkFinalTypeQ2

                    "Q3" ->
                        Json.Decode.succeed MarkFinalTypeQ3

                    "Q4" ->
                        Json.Decode.succeed MarkFinalTypeQ4

                    "H1" ->
                        Json.Decode.succeed MarkFinalTypeH1

                    "H2" ->
                        Json.Decode.succeed MarkFinalTypeH2

                    "Y" ->
                        Json.Decode.succeed MarkFinalTypeY

                    "E" ->
                        Json.Decode.succeed MarkFinalTypeE

                    "F" ->
                        Json.Decode.succeed MarkFinalTypeF

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



messageDecoder : Json.Decode.Decoder Message
messageDecoder =
    Json.Decode.succeed Message
        |> maybeDecode "id" Uuid.decoder Nothing
        |> maybeDecode "body" Json.Decode.string Nothing
        |> decode "sent_at" Api.Time.dateTimeDecoder 
        |> decode "sender" Uuid.decoder 
        |> maybeDecode "attachments" (Json.Decode.list Uuid.decoder) Nothing


messageNewsDecoder : Json.Decode.Decoder MessageNews
messageNewsDecoder =
    Json.Decode.succeed MessageNews
        |> maybeDecode "id" Uuid.decoder Nothing
        |> maybeDecode "body" Json.Decode.string Nothing
        |> decode "sent_at" Api.Time.dateTimeDecoder 
        |> decode "sender" Uuid.decoder 
        |> maybeDecode "attachments" (Json.Decode.list Uuid.decoder) Nothing


messagePrivateDecoder : Json.Decode.Decoder MessagePrivate
messagePrivateDecoder =
    Json.Decode.succeed MessagePrivate
        |> maybeDecode "id" Uuid.decoder Nothing
        |> maybeDecode "body" Json.Decode.string Nothing
        |> decode "sent_at" Api.Time.dateTimeDecoder 
        |> decode "sender" Uuid.decoder 
        |> decode "receiver" Uuid.decoder 
        |> maybeDecode "attachments" (Json.Decode.list Uuid.decoder) Nothing


messageTaskSubmissionDecoder : Json.Decode.Decoder MessageTaskSubmission
messageTaskSubmissionDecoder =
    Json.Decode.succeed MessageTaskSubmission
        |> maybeDecode "id" Uuid.decoder Nothing
        |> maybeDecode "body" Json.Decode.string Nothing
        |> decode "sent_at" Api.Time.dateTimeDecoder 
        |> decode "sender" Uuid.decoder 
        |> decode "receiver" Uuid.decoder 
        |> decode "activity" Uuid.decoder 
        |> maybeDecode "attachments" (Json.Decode.list Uuid.decoder) Nothing


organizationDecoder : Json.Decode.Decoder Organization
organizationDecoder =
    Json.Decode.succeed Organization
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "name" Json.Decode.string 
        |> maybeDecodeNullable "name_short" Json.Decode.string Nothing


setPasswordDecoder : Json.Decode.Decoder SetPassword
setPasswordDecoder =
    Json.Decode.succeed SetPassword
        |> decode "password" Json.Decode.string 


tokenDecoder : Json.Decode.Decoder Token
tokenDecoder =
    Json.Decode.succeed Token
        |> decode "user" userDecoder 
        |> decode "key" Json.Decode.string 


unreadObjectDecoder : Json.Decode.Decoder UnreadObject
unreadObjectDecoder =
    Json.Decode.succeed UnreadObject
        |> maybeDecode "id" Uuid.decoder Nothing
        |> decode "obj" Uuid.decoder 
        |> maybeDecode "type" unreadObjectTypeDecoder Nothing
        |> decode "created" Api.Time.dateTimeDecoder 
        |> decode "user" Uuid.decoder 


unreadObjectTypeDecoder : Json.Decode.Decoder UnreadObjectType
unreadObjectTypeDecoder =
    Json.Decode.string
        |> Json.Decode.andThen
            (\value ->
                case value of
                    "MSG" ->
                        Json.Decode.succeed UnreadObjectTypeMSG

                    "MRK" ->
                        Json.Decode.succeed UnreadObjectTypeMRK

                    "CRS" ->
                        Json.Decode.succeed UnreadObjectTypeCRS

                    "ACT" ->
                        Json.Decode.succeed UnreadObjectTypeACT

                    "NWS" ->
                        Json.Decode.succeed UnreadObjectTypeNWS

                    "EDU" ->
                        Json.Decode.succeed UnreadObjectTypeEDU

                    "FLE" ->
                        Json.Decode.succeed UnreadObjectTypeFLE

                    "FRM" ->
                        Json.Decode.succeed UnreadObjectTypeFRM

                    "TSK" ->
                        Json.Decode.succeed UnreadObjectTypeTSK

                    "UNK" ->
                        Json.Decode.succeed UnreadObjectTypeUNK

                    other ->
                        Json.Decode.fail <| "Unknown type: " ++ other
            )



userDecoder : Json.Decode.Decoder User
userDecoder =
    Json.Decode.succeed User
        |> maybeDecode "id" Uuid.decoder Nothing
        |> maybeDecodeNullable "last_login" Api.Time.dateTimeDecoder Nothing
        |> maybeDecode "is_superuser" Json.Decode.bool Nothing
        |> decode "username" Json.Decode.string 
        |> maybeDecode "first_name" Json.Decode.string Nothing
        |> maybeDecode "last_name" Json.Decode.string Nothing
        |> maybeDecode "email" Json.Decode.string Nothing
        |> maybeDecode "is_staff" Json.Decode.bool Nothing
        |> maybeDecode "is_active" Json.Decode.bool Nothing
        |> maybeDecode "date_joined" Api.Time.dateTimeDecoder Nothing
        |> maybeDecodeNullable "middle_name" Json.Decode.string Nothing
        |> maybeDecodeNullable "birth_date" Api.Time.dateDecoder Nothing
        |> maybeDecodeNullable "avatar" Json.Decode.string Nothing
        |> maybeDecode "groups" (Json.Decode.list Json.Decode.int) Nothing
        |> maybeDecode "user_permissions" (Json.Decode.list Json.Decode.int) Nothing
        |> maybeDecode "children" (Json.Decode.list Uuid.decoder) Nothing




-- HELPER


type alias EncodedField =
    Maybe ( String, Json.Encode.Value )


encodeObject : List EncodedField -> Json.Encode.Value
encodeObject =
    Json.Encode.object << List.filterMap identity


encode : String -> (a -> Json.Encode.Value) -> a -> EncodedField
encode key encoder value =
    Just ( key, encoder value )


encodeNullable : String -> (a -> Json.Encode.Value) -> Maybe a -> EncodedField
encodeNullable key encoder value =
    Just ( key, Maybe.withDefault Json.Encode.null (Maybe.map encoder value) )


maybeEncode : String -> (a -> Json.Encode.Value) -> Maybe a -> EncodedField
maybeEncode key encoder =
    Maybe.map (Tuple.pair key << encoder)


maybeEncodeNullable : String -> (a -> Json.Encode.Value) -> Maybe a -> EncodedField
maybeEncodeNullable =
    encodeNullable


decode : String -> Json.Decode.Decoder a -> Json.Decode.Decoder (a -> b) -> Json.Decode.Decoder b
decode key decoder =
    decodeChain (Json.Decode.field key decoder)


decodeLazy : (a -> c) -> String -> Json.Decode.Decoder a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
decodeLazy f key decoder =
    decodeChainLazy f (Json.Decode.field key decoder)


decodeNullable : String -> Json.Decode.Decoder a -> Json.Decode.Decoder (Maybe a -> b) -> Json.Decode.Decoder b
decodeNullable key decoder =
    decodeChain (maybeField key decoder Nothing)


decodeNullableLazy : (Maybe a -> c) -> String -> Json.Decode.Decoder a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
decodeNullableLazy f key decoder =
    decodeChainLazy f (maybeField key decoder Nothing)


maybeDecode : String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (Maybe a -> b) -> Json.Decode.Decoder b
maybeDecode key decoder fallback =
    -- let's be kind to null-values as well
    decodeChain (maybeField key decoder fallback)


maybeDecodeLazy : (Maybe a -> c) -> String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
maybeDecodeLazy f key decoder fallback =
    -- let's be kind to null-values as well
    decodeChainLazy f (maybeField key decoder fallback)


maybeDecodeNullable : String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (Maybe a -> b) -> Json.Decode.Decoder b
maybeDecodeNullable key decoder fallback =
    decodeChain (maybeField key decoder fallback)


maybeDecodeNullableLazy : (Maybe a -> c) -> String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
maybeDecodeNullableLazy f key decoder fallback =
    decodeChainLazy f (maybeField key decoder fallback)


maybeField : String -> Json.Decode.Decoder a -> Maybe a -> Json.Decode.Decoder (Maybe a)
maybeField key decoder fallback =
    let
        fieldDecoder =
            Json.Decode.field key Json.Decode.value

        valueDecoder =
            Json.Decode.oneOf [ Json.Decode.map Just decoder, Json.Decode.null fallback ]

        decodeObject rawObject =
            case Json.Decode.decodeValue fieldDecoder rawObject of
                Ok rawValue ->
                    case Json.Decode.decodeValue valueDecoder rawValue of
                        Ok value ->
                            Json.Decode.succeed value

                        Err error ->
                            Json.Decode.fail (Json.Decode.errorToString error)

                Err _ ->
                    Json.Decode.succeed fallback
    in
    Json.Decode.value
        |> Json.Decode.andThen decodeObject


decodeChain : Json.Decode.Decoder a -> Json.Decode.Decoder (a -> b) -> Json.Decode.Decoder b
decodeChain =
    Json.Decode.map2 (|>)


decodeChainLazy : (a -> c) -> Json.Decode.Decoder a -> Json.Decode.Decoder (c -> b) -> Json.Decode.Decoder b
decodeChainLazy f =
    decodeChain << Json.Decode.map f